version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static  # <-- bind the static volume
      - media_volume:/backend/media  # <-- bind the media volume
    env_file:
      - ./.prod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    volumes:
      - static_volume:/backend/static  # <-- bind the static volume
      - media_volume:/backend/media  # <-- bind the media volume

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume